hooks:
  highfive:
    enabled: false
  assigner:
    enabled: false
    # weekly or issue
    rotation: weekly
    pool:
      - user_id_001
      - user_id_002
      - user_id_003
    override: user_id_004
  forcepush:
    enabled: false
  prlabels:
    enabled: false
    patterns:
      - pattern: file_path_regex_pattern_1
        labels:
          - label_1
      - pattern: ile_path_regex_pattern_2
        labels:
          - label_2